Fix EnvoyFilter for Istio 1.7
kyma-incubator/compass pull request #1555
Opened 2020-10-08 15:10 UTC by Tomasz-Smelcerz-SAP

**Description**
Updated EnvoyFilter syntax for Istio 1.7
Do not merge, it should be conditionally enabled for 1.7 and disabled for old Istio versions.

Changes proposed in this pull request:

- Updated EnvoyFilter syntax for Istio 1.7

**Related issue(s)**
See also: https://github.com/kyma-project/kyma/pull/9503/files

2020-10-08 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/compass?pullRequest=1555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/compass?pullRequest=1555) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/compass?pullRequest=1555) it.</sub>

2020-10-09 06:10 UTC, piotrmsc commented on chart/compass/templates/rewrite-client-cert-filter.yaml
> +          typed_config:
it won't simply work this way. Compass repo is still running on kyma version with istio 1.4.

2020-10-09 06:21 UTC, piotrmsc commented
/test pre-master-compass-gke-integration

2020-10-09 06:37 UTC, Demonsthere commented on chart/compass/templates/rewrite-token-filter.yaml
> +            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
```suggestion
         {{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1/PeerAuthentication" }}
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          {{- end }}
```

2020-10-09 06:37 UTC, Demonsthere commented on chart/compass/templates/rewrite-client-cert-filter.yaml
> +            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
```suggestion
          {{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1/PeerAuthentication" }}
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          {{- end }} 
```

2020-10-09 06:46 UTC, Demonsthere commented
/test all

2020-10-09 06:50 UTC, Demonsthere requested changes

2020-10-09 06:50 UTC, Demonsthere commented on chart/compass/templates/rewrite-token-filter.yaml
> +            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
```suggestion
          {{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1/PeerAuthentication" }}
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          {{- else }}
          config:
          {{- end }} 
```

2020-10-09 06:50 UTC, Demonsthere commented on chart/compass/templates/rewrite-client-cert-filter.yaml
> +            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
```suggestion
          {{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1/PeerAuthentication" }}
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          {{- else }}
          config:
          {{- end }} 
```

2020-10-09 07:14 UTC, Demonsthere commented
/test pre-master-compass-integration

2020-10-09 07:22 UTC, Demonsthere commented
/test pre-master-compass-development-artifacts

2020-10-09 07:25 UTC, Demonsthere commented
/retest

2020-10-09 07:35 UTC, Demonsthere commented
/retest

2020-10-09 08:35 UTC, Demonsthere commented
/retest

2020-10-09 08:48 UTC, suleymanakbas91 commented
/retest

2020-10-09 08:52 UTC, Demonsthere approved these changes

2020-10-09 09:07 UTC, rafalpotempa approved these changes

2020-10-09 09:12 UTC, merged