Add client_user header into the Director's CORS config and update UI reference
kyma-incubator/compass pull request #1742
Opened 2021-02-23 09:34 UTC by danielgospodinow

**Description**

This PR fixes the issue with SFSF/C4C application connection in the Compass UI.

Changes proposed in this pull request:
- Change the virtual service of the Gateway component to setup the `client_user` header in the Director's CORS configuration.
- Update Compass UI reference.

**Pull Request status**

- [x] Implementation
- [x] `chart/compass/values.yaml` is updated

2021-02-23 11:41 UTC, danielgospodinow commented
/test pre-master-compass-gke-integration

2021-02-23 11:41 UTC, danielgospodinow commented
/retest

2021-02-23 13:29 UTC, danielgospodinow commented
/retest

2021-02-24 15:58 UTC, danielgospodinow commented
/retest

2021-02-25 07:18 UTC, danielgospodinow commented
/retest

2021-02-25 12:42 UTC, alextargov submitted a review, later dismissed

2021-02-25 14:37 UTC, alextargov submitted a review, later dismissed

2021-02-26 07:29 UTC, NickyMateev requested changes

2021-02-26 07:29 UTC, NickyMateev commented on chart/compass/charts/gateway/templates/virtualservice.yaml
> +          - "client_user"
Don't forget to not leave the value hard coded here and in the other virtualservice file as well

2021-02-26 08:02 UTC, NickyMateev approved these changes

2021-02-26 08:17 UTC, merged