Update half of the components
kyma-incubator/compass pull request #1828
Opened 2021-04-13 08:12 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated

2021-04-13 09:31 UTC, alextargov commented
/test pre-compass-components-operations-controller

2021-04-14 07:05 UTC, alextargov commented
/retest

2021-04-14 10:03 UTC, alextargov commented
/retest

2021-04-14 11:21 UTC, alextargov commented
/retest

2021-04-16 05:56 UTC, desislavaa reviewed
The E2E tests Dockerfile can also be updated with Go v16

2021-04-16 08:15 UTC, dzahariev reviewed
In addition:
Update schema migrator image to 3.13.5

All those changes are part of PR: https://github.com/kyma-incubator/compass/pull/1836
It was created only to validate proposed changes. 
If you prefer to not add those changes here, but to rebase the PR later, let me know, otherwise I will abandon my PR once the proposed changes are part of this one.

2021-04-16 09:56 UTC, alextargov commented
/retest

2021-04-16 10:24 UTC, dzahariev approved these changes

2021-04-16 10:27 UTC, dzahariev requested changes

2021-04-16 10:27 UTC, dzahariev commented on chart/compass/values.yaml
>        version: "PR-1780"
Update also schema migrator image.

2021-04-16 11:15 UTC, alextargov commented
/retest

2021-04-19 07:05 UTC, alextargov commented
/retest

2021-04-19 08:05 UTC, alextargov commented
/retest

2021-04-19 08:12 UTC, alextargov commented
/retest

2021-04-19 12:37 UTC, dzahariev commented on components/operations-controller/Dockerfile
Please add "-x" fo download (to get download feedback during build) on line 10:
```
RUN go mod download -x
```

2021-04-19 13:08 UTC, alextargov commented
/retest

2021-04-19 13:16 UTC, alextargov commented
/retest

2021-04-19 13:18 UTC, dzahariev approved these changes

2021-04-19 13:57 UTC, merged