Delete eventing label
kyma-incubator/compass pull request #1960
Opened 2021-07-21 11:34 UTC by StefanCholakov

-Delete default eventing label, when removing from formation

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [ ] `chart/compass/values.yaml` is updated
- [x] Mocks are regenerated, using the automated script

2021-07-21 12:14 UTC, StefanCholakov commented
/retest

2021-07-21 14:07 UTC, DimitarPetrov requested changes

2021-07-21 14:07 UTC, DimitarPetrov commented on components/director/internal/domain/eventing/service_test.go
> +		require.Equal(t, emptyConfiguration, conf)
This test relies on that the GetByKey returns NotFound and then on the second time on 187 line no runtime is found and therefore emptyConfig.

However, I think it makes sense to add a test that on the second execution on GetByKey returns a real runtime and therefore validate the full flow.

1. Get defatul eventing
2. See that there is no scenario anymore
3. Delete the default eventing
4. Get new runtime in scenario with the APP
5. Add default eventing to it
6. Return real config

2021-07-22 07:52 UTC, StefanCholakov commented
/retest

2021-07-22 10:41 UTC, NickyMateev approved these changes

2021-07-22 11:12 UTC, merged