Whitelist ott for graphql schema
kyma-incubator/compass pull request #2007
Opened 2021-09-03 12:13 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2021-09-07 13:38 UTC, alextargov commented
/retest

2021-09-07 14:18 UTC, alextargov commented
/retest

2021-09-09 08:25 UTC, alextargov commented
/retest

2021-09-09 14:05 UTC, alextargov commented on components/director/internal/domain/application/resolver.go
> +		if sa.Value.OneTimeToken != nil && sa.Value.OneTimeToken.Type == tokens.ApplicationToken {
Not sure if we'd like to expose the OTT for other types than Applications at the moment. Probably if there's a need to expose them as well, it won't be much of an effort.

2021-09-09 14:30 UTC, pankrator requested changes

2021-09-09 14:30 UTC, pankrator commented on components/director/internal/domain/application/resolver.go
> +func (r *Resolver) checkApplicationOneTimeTokenIsInvalid(auth *model.Auth, config onetimetoken.Config) bool {
maybe `isApplicationOTTInvalid`

2021-09-09 14:30 UTC, pankrator commented on components/director/internal/domain/application/resolver.go
> +	}
There is the following portion of code in file `validation_hydrator.go`:
```
expirationTime, err := vh.getExpirationTimeForToken(systemAuth)
	if err != nil {
		log.C(ctx).Error(err)
		respondWithAuthSession(ctx, w, authSession)
		return
	}

	if systemAuth.Value.OneTimeToken.CreatedAt.Add(expirationTime).Before(vh.timeService.Now()) {
		log.C(ctx).Infof("One Time Token with validity %s for system auth with ID %q has expired", expirationTime.String(), systemAuth.ID)
		respondWithAuthSession(ctx, w, authSession)
		return
	}
```

The code for expiration can be extracted in common function

2021-09-09 14:30 UTC, pankrator commented on components/director/pkg/graphql/schema.graphql
> +	oneTimeToken: OneTimeTokenForApplication
In my opinion, this should work for all kind of OTT, not only Application, as the type is Auth, which is generic.

2021-09-09 14:30 UTC, pankrator commented on tests/connector/tests/hydrator_api_test.go
> +			app, err := fixtures.RegisterApplicationFromInput(t, ctx, directorClient.DexGraphqlClient, cfg.Tenant, graphql.ApplicationRegisterInput{
Why was it needed to move app creation for each test case and check inside the clientID which has to be passed to `tokenGenerationFunc`?

2021-09-09 15:15 UTC, ataleksandrov commented on tests/connector/tests/hydrator_api_test.go
> -	app, err := fixtures.RegisterApplicationFromInput(t, ctx, directorClient.DexGraphqlClient, cfg.Tenant, graphql.ApplicationRegisterInput{
Not sure, why this is needed?

2021-09-09 17:23 UTC, alextargov commented on components/director/pkg/graphql/schema.graphql
> +	oneTimeToken: OneTimeTokenForApplication
No, that would be generic. You would do 

` oneTimeToken {
            ... on OneTimeTokenForApplication {
              token
              connectorURL
              legacyConnectorURL
            }
          }`

or 
` oneTimeToken {
            ... on OneTimeTokenForRuntime {
              token
              connectorURL
            }
          }`

2021-09-10 13:26 UTC, ataleksandrov commented on components/director/internal/domain/onetimetoken/service.go
> +	if !s.isAuthOneTimeTokenType(systemAuth) {
Could we just check `systemAuth.Value.OneTimeToken == nil`?

2021-09-10 13:26 UTC, ataleksandrov commented on components/director/internal/oathkeeper/validation_hydrator.go
> +//go:generate mockery --name=SystemAuthService --output=automock --outpkg=automock --case=underscore
Could you please delete the previous mock file?

2021-09-10 13:26 UTC, ataleksandrov commented on tests/connector/tests/hydrator_api_test.go
> -		clientId             string
Having unified `cliet_id`, removes the need of` if testCase.clientType == "Application" {` everywhere except in the check here: https://github.com/kyma-incubator/compass/pull/2007/files#diff-c5b72ac3ff812b64b53e2ea366f61ea7068307ff8b5e7e8ce07b5e19e4de84daR104 , so I would propose to return it.

2021-09-10 13:56 UTC, pankrator requested changes

2021-09-10 13:56 UTC, pankrator commented on components/director/internal/api/token_resolver.go
> +	IsTokenValid(systemAuth *model.SystemAuth) (bool, error)
This seems like it is not used

2021-09-10 13:56 UTC, pankrator commented on components/director/internal/oathkeeper/validation_hydrator_test.go
> +		//timeService.On("Now").Return(beforeOneDay)
Delete this

2021-09-10 13:56 UTC, pankrator commented on components/director/internal/oathkeeper/validation_hydrator_test.go
> +		//timeService.On("Now").Return(beforeOneDay)
Leftover?

2021-09-10 13:56 UTC, pankrator commented on tests/connector/tests/hydrator_api_test.go
> +			if testCase.clientType == "Application" {
As Acho pointed out this snippets can be simplified (like it was before) as they are identical in each test case

2021-09-13 05:03 UTC, alextargov commented
/retest

2021-09-13 06:36 UTC, alextargov commented
/retest

2021-09-13 10:32 UTC, pankrator commented
/retest

2021-09-13 11:01 UTC, pankrator approved these changes

2021-09-13 15:11 UTC, pankrator commented
/lgtm

2021-09-13 15:12 UTC, merged