Final adaptations for System Fetcher mTLS
kyma-incubator/compass pull request #2202
Opened 2022-02-02 18:18 UTC by danielgospodinow

**Description**

Enable only mTLS communication in the System Fetcher component.

**Pull Request status**

- [x] Implementation
- [ ] *N/A* Unit tests
- [ ] *N/A* Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] *N/A* Mocks are regenerated, using the automated script

2022-02-03 00:06 UTC, danielgospodinow commented
/retest

2022-02-07 14:05 UTC, danielgospodinow commented
/retest

2022-02-09 07:02 UTC, PetarTodorovv requested changes

2022-02-09 07:07 UTC, PetarTodorovv commented
As part of https://github.com/kyma-incubator/compass/pull/2206 I have to make these changes as well so we can briefly discuss it and eventually close this PR?

2022-02-09 14:24 UTC, danielgospodinow commented on chart/compass/templates/system-fetcher-job.yaml
> +  {{ end }}
I've left it only for backwards compatibility.

2022-02-09 16:35 UTC, danielgospodinow commented on chart/compass/templates/system-fetcher-job.yaml
> +  {{ end }}
I removed it.

2022-02-09 16:41 UTC, danielgospodinow commented on chart/compass/values.yaml
> -      clientSecretKey: client-secret
I'm not sure what has to be done additionally in the `config` repo.

2022-02-09 16:46 UTC, danielgospodinow commented on installation/resources/installer-config-local.yaml.tpl
> -  global.systemFetcher.oauth.skipSSLValidation: "true"
Sure, I guess there can be more properties that can be removed. I just removed only those relevant to the task. I can take care of the remaining ones as well.

2022-02-15 09:19 UTC, PetarTodorovv approved these changes

2022-02-15 09:21 UTC, merged