Replace Dex GraphQL client in E2E tests
kyma-incubator/compass pull request #2222
Opened 2022-02-24 17:57 UTC by danielgospodinow

**Description**

As part of the process of removing Dex from our architecture, this PR introduces dex removal in our e2e tests.

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-03-02 13:09 UTC, DimitarPetrov commented
/retest

2022-03-04 08:06 UTC, DimitarPetrov commented
/hold

2022-03-04 08:11 UTC, DimitarPetrov commented
/retest

2022-03-04 08:31 UTC, DimitarPetrov commented
/test pre-compass-tests

2022-03-04 08:41 UTC, DimitarPetrov commented
/retest

2022-03-04 08:47 UTC, DimitarPetrov commented
/retest

2022-03-07 07:45 UTC, DimitarPetrov commented
/test pre-compass-tests

2022-03-07 08:25 UTC, DimitarPetrov commented
/retest

2022-03-07 14:08 UTC, StanislavStefanov requested changes

2022-03-07 14:08 UTC, StanislavStefanov commented on tests/pkg/config/system_broker.go
> +	DirectorURL                    string
Seems like this is unused

2022-03-07 14:08 UTC, StanislavStefanov commented on tests/pkg/testctx/broker/system_broker_testctx.go
> +	DirectorURL                    string
Seems like this is unused

2022-03-07 15:28 UTC, DimitarPetrov commented on tests/istio/tests/main_test.go
> +	var err error
It is because the `testctx.Tc` on the leftside of the assignment below is not a new variable.
```
testctx.Tc, err = testctx.NewTestContext()
```

2022-03-09 09:56 UTC, StanislavStefanov requested changes

2022-03-09 09:56 UTC, StanislavStefanov commented on tests/ns-adapter/tests/main_test.go
> +	DirectorURL                    string        `envconfig:"DIRECTOR_URL"`
Domain and DirectorURL should be removed as they are removed from the test definition

2022-03-09 10:24 UTC, StanislavStefanov approved these changes

2022-03-09 10:49 UTC, DimitarPetrov commented
/hold cancel

2022-03-09 14:20 UTC, StanislavStefanov approved these changes

2022-03-09 14:38 UTC, merged