Improve documentation on security topics
kyma-incubator/compass pull request #2243
Opened 2022-03-08 14:24 UTC by desislavaa

**Description**
Documentation improvements on the follwing aspects:
- Consumer-provider flow documentaton (SaaS app)
- Consumer-provider flow documentaton (Integration System)
- Internal Authentication
- Filters

2022-03-10 12:00 UTC, desislavaa commented on chart/compass/templates/filters/limit-request-payload-size.yaml
> +apiVersion: networking.istio.io/v1alpha3
remove

2022-03-21 16:08 UTC, DimitarPetrov requested changes

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +When the multi-tenant system is represented as a Runtime, its tenant access is managed from an outside service, which communicates with the Tenant Fetcher deployment, and grants the consumer tenant (
consumer and provider are switched here.

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +If the consumer tenant has access to the type of tenant the provider belongs to, then the request is authorized successfully.
consumer and provider are switched here.

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +**Compass ORD Service Flow:**
This one is productive already.

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +The first context provider will return Runtime scopes, and the second one will return the scopes present in the JWT. We should use the ones from the token.
Not sure this is true, let's sync offline.

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-02-filters.md
> +This filter was introduced because there are no timeouts on ARY Oathkeeper side, but we want to cancel requests that take more time than usual.
typo ARY -> ORY

2022-03-21 16:08 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +![](./assets/internal-auth.png)
Not rendered.

2022-04-11 11:55 UTC, nkanchev approved these changes

2022-04-12 09:27 UTC, DimitarPetrov requested changes

2022-04-12 09:27 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> + - SaaS applications, which are modeled like runtimes, can access Compass resources with an externally-issued certificate, and a JWT where the provider tenant is present.
... and a JWT where the `consumer` tenant is present

2022-04-12 09:27 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +- The multi-tenant system is represented as a Runtime. In this case, the second context provider that matches is a custom authenticator, where the provider tenant is part of a JWT, along with the sco
... where the `consumer` tenant is part of a JWT ...

2022-04-12 09:27 UTC, DimitarPetrov commented on docs/compass/03-01-security.md
> +Both cases feature two context providers, which are used in a pair. One of context providers must be an externally-issued certificate context provider. It extracts the consumer tenant ID from the cer
In the whole doc consumer and provider seems to be switched based on compass perspective. 

provider - the tenant providing system metadata (like ORD provider)
consumer - the tenant consuming system metadata (like ORD consumer)

However, the most common use of those terms in the SaaS registry world are from the SaaS app's perspective:

provider - the SaaS application that provides some features to a client
consumer - the client that consumes those features

Maybe we can stick to this terminology as most widely used in other resources.

2022-04-12 10:15 UTC, DimitarPetrov approved these changes

2022-04-12 10:27 UTC, nkanchev approved these changes

2022-04-12 10:37 UTC, merged