Automatic Scenario Assignments documentation updates
kyma-incubator/compass pull request #2253
Opened 2022-03-18 06:28 UTC by desislavaa

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-03-22 13:05 UTC, DimitarPetrov requested changes

2022-03-22 13:05 UTC, DimitarPetrov commented on docs/compass/03-03-automatic-scenario-assignment.md
> +Then, if a Runtime is labeled with `global_subaccount_id`, the Runtime is assigned to the given Scenario, even though they are in different tenants.
There is no more label processing. The scenario assignment is based on the tenant that the runtime is registered in.

We can add a few sentences that previously it was label selector and now it is subaccount_id selector and the interface is kept for backwards compatibility, but the only key possible is global_subaccount_id. Then the tenant of the runtime is checked and not labels anymore.

2022-04-11 11:37 UTC, nkanchev approved these changes

2022-04-13 10:52 UTC, DimitarPetrov approved these changes

2022-04-13 11:04 UTC, nkanchev approved these changes

2022-04-13 11:06 UTC, merged