Add logs from jobs started from e2e tests
kyma-incubator/compass pull request #2282
Opened 2022-03-25 13:58 UTC by la4ezar

**Description**
Add logs from jobs started from e2e tests

Changes proposed in this pull request:
- Currently, the e2e tests for system-fetcher, tenant-fetcher, and ord-service(in the self-register flow cert-rotation job is created) create tests as part of the test. Logs from these jobs should be redirected to the standard output so that the logs remain even after the pod has been deleted.

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-03-28 06:28 UTC, la4ezar commented
/retest

2022-03-29 06:41 UTC, PetarTodorovv commented on tests/pkg/k8s/jobs.go
> +func PrintJobLogs(t *testing.T, ctx context.Context, k8sClient *kubernetes.Clientset, jobName, namespace, containerName string) {
can we somehow get the pod's logs only if it fails and have error? Or the logs from these jobs(system/tenant fetcher, cert-rotation-job, etc..) are not too verbose and it won't be a problem?

2022-03-29 07:21 UTC, la4ezar commented on tests/system-fetcher/tests/handler_test.go
> +	systemFetcherContainerName = "system-fetcher"
Yes, I think it will be much better if we extract the container names.

2022-03-29 09:08 UTC, NickyMateev requested changes

2022-03-29 09:08 UTC, NickyMateev commented on chart/compass/values.yaml
> +    containerName: "system-fetcher"
Make use of this in `system-fetcher-job.yaml` where the container name is defined, otherwise this is double maintenance

2022-03-29 12:04 UTC, NickyMateev approved these changes

2022-03-29 12:50 UTC, la4ezar commented
/retest

2022-03-30 06:17 UTC, la4ezar commented
/retest

2022-03-30 07:23 UTC, la4ezar commented
/retest

2022-03-30 08:35 UTC, la4ezar commented
/retest

2022-03-30 09:08 UTC, la4ezar commented
/retest

2022-03-30 09:43 UTC, la4ezar commented
/retest

2022-03-30 11:12 UTC, la4ezar commented
/retest

2022-03-30 12:10 UTC, la4ezar commented
/test pre-compass-tests

2022-03-30 12:28 UTC, la4ezar commented
/retest

2022-03-30 14:33 UTC, NickyMateev approved these changes

2022-03-30 14:51 UTC, desislavaa approved these changes

2022-03-30 14:52 UTC, merged