Tfd api
kyma-incubator/compass pull request #2294
Opened 2022-03-30 15:37 UTC by inaand

**Description**

New API to fetch on-demand newly created tenants and store them 

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-04-12 08:04 UTC, la4ezar requested changes

2022-04-14 06:09 UTC, desislavaa reviewed
Some minor comments

2022-04-14 06:09 UTC, desislavaa commented on components/director/internal/tenantfetcher/service_test.go
> +		ExpectedError      error
This can be changed to "ExpectedErrorMsg" because we only use the cause

2022-04-14 06:09 UTC, desislavaa commented on components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
> +		ExpectedError      error
Same here with the `ExpectedErrorMsg`

2022-04-14 06:09 UTC, desislavaa commented on components/director/internal/tenantfetchersvc/handler.go
> +// FetchTenantOnDemand fetches CIS events for a provided subaccount and creates a tenant
CIS -> External tenants registry (I'm pretty sure it's already referenced as CIS somewhere, but still) 😄

2022-04-14 06:09 UTC, desislavaa commented on components/director/internal/tenantfetchersvc/handler.go
> +	err := h.fetcher.FetchTenantOnDemand(ctx, tenantID)
We can add an Info log like "Fetching create event for tenant with ID %s"

2022-04-14 06:09 UTC, desislavaa commented on components/director/internal/tenantfetchersvc/handler.go
> +		log.C(ctx).Error("Tenant path parameter is missing from request")
`log.C(ctx).WithError(err)...` <- this adds the error as `error` field in the json log message - it looks pretty in Kibana.
Same on L114

2022-04-15 14:31 UTC, inaand commented
/retest

2022-04-18 11:55 UTC, inaand commented
/retest

2022-04-18 14:09 UTC, inaand commented
/retest

2022-04-19 11:26 UTC, inaand commented
/retest

2022-04-19 14:51 UTC, inaand commented
/retest

2022-04-20 10:54 UTC, la4ezar approved these changes

2022-04-20 10:54 UTC, merged