Enable Assigning a single Runtime to formation in the new Formation APIs
kyma-incubator/compass pull request #2309
Opened 2022-04-14 07:39 UTC by la4ezar

**Description**
Enable Assigning a single Runtime to formation without adding the subaccount of the runtime to the formation (Without ASA) in the new Formation APIs.

Changes proposed in this pull request:
- Introduce FormationObjectTypeRuntime and process it accordingly in the new formations APIs.

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-04-14 07:57 UTC, DimitarPetrov commented on components/director/internal/domain/formation/fixtures_test.go
> +}
Unneccessary wrapping. You can directly return the service and use this function as a `func() *automock.LabelService`

2022-04-20 09:54 UTC, StanislavStefanov requested changes

2022-04-20 09:54 UTC, StanislavStefanov commented on components/director/internal/domain/formation/service.go
> +		return s.modifyAssignedFormations(ctx, tnt, objectID, formation, model.ApplicationLabelableObject, deleteFormation)
Use objectTypeToLabelableObject(objectType) instead of hardcoding the objectType

2022-04-20 09:54 UTC, StanislavStefanov commented on components/director/internal/domain/formation/service.go
> +		return s.modifyAssignedFormations(ctx, tnt, objectID, formation, model.RuntimeLabelableObject, deleteFormation)
Use objectTypeToLabelableObject(objectType) instead of hardcoding the objectType

2022-04-20 09:54 UTC, StanislavStefanov commented on components/director/internal/domain/formation/service_test.go
> +			Name:         "success for runtime if formation do not exist",
This testCase is the same as "success for runtime". Should use different InputFormation that is not part of the assigned formations

2022-04-20 09:54 UTC, StanislavStefanov commented on components/director/internal/domain/scenarioassignment/engine_test.go
> +			Name:           "Returns error when can't list ASAs",
The name is incorrect

2022-04-20 09:54 UTC, StanislavStefanov commented on tests/director/tests/formation_api_test.go
> +
Can we verify that the fomation value is not present in the label after the unassignment here using checkRuntimeFormationLabels

2022-04-20 13:00 UTC, la4ezar commented
/retest

2022-04-20 14:02 UTC, la4ezar commented
/retest

2022-04-21 10:15 UTC, StanislavStefanov approved these changes

2022-04-21 11:18 UTC, la4ezar commented
/test pre-main-compass-gke-benchmark

2022-04-21 12:33 UTC, la4ezar commented
/retest

2022-04-21 19:26 UTC, la4ezar commented
/retest

2022-04-21 20:08 UTC, la4ezar commented
/retest

2022-04-21 21:48 UTC, la4ezar commented
/retest

2022-04-21 23:22 UTC, la4ezar commented
/retest

2022-04-26 06:35 UTC, la4ezar commented
/retest

2022-04-26 07:57 UTC, la4ezar commented
/retest

2022-04-26 08:20 UTC, StanislavStefanov approved these changes

2022-04-26 09:50 UTC, la4ezar commented
/retest

2022-04-26 10:06 UTC, StanislavStefanov commented
/hold cancel

2022-04-26 10:51 UTC, StanislavStefanov approved these changes

2022-04-26 10:51 UTC, merged