Adapt Application Label API to use Formations API
kyma-incubator/compass pull request #2386
Opened 2022-05-26 09:14 UTC by ivantenevvasilev

**Description**

Changes proposed in this pull request:
- adapt `registerApplication` to use Formations API for scenario label
- adapt `setApplicationLabel` to use Formations API for scenario label
- adapt `deleteApplicationLabel` to use Formations API for scenario label
- adapt old unit tests
- introduce new unit tests to cover new cases

**Related issue(s)**
- ...

**Pull Request status**

- [x] Implementation
- [ ] Unit tests
- [ ] `chart/compass/values.yaml` is updated
- [x] Mocks are regenerated, using the automated script

2022-05-30 13:03 UTC, dzahariev submitted a review, later dismissed

2022-06-01 06:09 UTC, StanislavStefanov submitted a review, later dismissed

2022-06-01 08:06 UTC, ivantenevvasilev commented on components/director/internal/domain/application/service.go
> +		scenarios, err := label.ValueToStringsSlice(labelValue)
nice catch

2022-06-01 11:03 UTC, ivantenevvasilev commented
/retest

2022-06-01 13:27 UTC, ivantenevvasilev commented
/test pre-main-compass-integration

2022-06-02 06:10 UTC, ivantenevvasilev commented
/retest

2022-06-02 08:00 UTC, ivantenevvasilev commented
/retest

2022-06-02 09:38 UTC, ivantenevvasilev commented
/retest

2022-06-02 13:27 UTC, dzahariev approved these changes

2022-06-02 15:33 UTC, ivantenevvasilev commented
/retest

2022-06-03 05:23 UTC, StanislavStefanov requested changes

2022-06-03 05:23 UTC, StanislavStefanov commented on components/director/internal/domain/application/service_test.go
> +			err := svc.DeleteLabel(ctx, testCase.InputApplicationID, testCase.InputKey) // TODO
leftover

2022-06-03 05:23 UTC, StanislavStefanov commented on components/director/internal/domain/application/service_test.go
> +			Name: "Returns error when application succeeds but application does not exist",
"Returns error when application does not exist" ?

2022-06-03 06:14 UTC, StanislavStefanov approved these changes

2022-06-03 06:53 UTC, StanislavStefanov approved these changes

2022-06-03 07:19 UTC, ivantenevvasilev commented
/test pre-main-compass-gke-benchmark

2022-06-03 08:35 UTC, dzahariev approved these changes

2022-06-03 08:50 UTC, ivantenevvasilev commented
/test pre-compass-components-director

2022-06-03 09:03 UTC, ivantenevvasilev commented
/retest

2022-06-03 09:03 UTC, ivantenevvasilev commented
/hold cancel

2022-06-03 10:41 UTC, ivantenevvasilev commented
/retest

2022-06-03 12:02 UTC, ivantenevvasilev commented
/retest

2022-06-03 13:34 UTC, ivantenevvasilev commented
/retest

2022-06-03 15:32 UTC, ivantenevvasilev commented
/test pre-compass-components-director

2022-06-03 16:43 UTC, ivantenevvasilev commented
/retest

2022-06-06 05:09 UTC, ivantenevvasilev commented
/retest

2022-06-06 06:55 UTC, ivantenevvasilev commented
/retest

2022-06-06 08:04 UTC, ivantenevvasilev commented
/retest

2022-06-06 09:40 UTC, ivantenevvasilev commented
/retest

2022-06-06 09:59 UTC, dzahariev approved these changes

2022-06-06 11:09 UTC, merged