Allow generating OTT for applications registered on subaccount level from Pairing Adapter
kyma-incubator/compass pull request #2393
Opened 2022-06-01 12:56 UTC by la4ezar

**Description**
Allow generating OTT for applications registered on subaccount level from Pairing Adapter

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-06-01 13:50 UTC, ivantenevvasilev commented on components/director/internal/domain/onetimetoken/service.go
> +			return nil, errors.Wrapf(err, "while getting tenant with external ID %q", tntCtx.ExternalID)
Is this if/else needed? We'll have the internal ID regardless and it'll be associated with an external tenant ID, so this branching of the code might not be needed and it'll make the mocking in the tests a bit easier, but in the end it's ok as is

2022-06-01 13:50 UTC, ivantenevvasilev commented on components/director/internal/domain/onetimetoken/service.go
> +		extTenant = tnt.ExternalTenant
Maybe set it by default to `tnt.ExternalTenant` above the check for subaccount? I think this might be a bit easier for readability.

2022-06-02 06:23 UTC, la4ezar commented
/retest

2022-06-02 07:59 UTC, la4ezar commented
/test pre-main-compass-integration

2022-06-03 05:50 UTC, StanislavStefanov submitted a review, later dismissed

2022-06-03 05:50 UTC, StanislavStefanov commented
/hold

2022-06-03 06:19 UTC, la4ezar commented
/test pre-main-compass-integration

2022-06-03 06:47 UTC, PetarTodorovv requested changes

2022-06-03 08:18 UTC, PetarTodorovv approved these changes

2022-06-15 13:50 UTC, la4ezar commented
/retest

2022-06-15 15:27 UTC, nyordanoff commented
/test pre-main-compass-gke-benchmark

2022-06-15 17:16 UTC, nyordanoff commented
/test pre-main-compass-gke-benchmark

2022-06-16 06:23 UTC, DimitarPetrov commented
/hold cancel

2022-06-16 06:25 UTC, StanislavStefanov approved these changes

2022-06-16 06:27 UTC, merged