Delete app from tmpl on unsubscription callback
kyma-incubator/compass pull request #2406
Opened 2022-06-07 13:06 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-06-07 14:20 UTC, alextargov commented
/retest

2022-06-07 14:20 UTC, alextargov commented
/test all

2022-06-09 09:17 UTC, kaloyanspiridonov requested changes

2022-06-09 09:17 UTC, kaloyanspiridonov commented on components/director/internal/domain/apptemplate/repository.go
> +func (r *repository) GetByFilters(ctx context.Context, filter []*labelfilter.LabelFilter) (*model.ApplicationTemplate, error) {
Add unit tests

2022-06-09 09:17 UTC, kaloyanspiridonov commented on components/director/internal/domain/apptemplate/service.go
> +// GetByFilters gets a model.ApplicationTemplate by given slice of labelfilter.LabelFilter
Add unit tests

2022-06-09 09:17 UTC, kaloyanspiridonov commented on tests/tenant-fetcher/tests/handler_test.go
> +		tmplName := "app-flow-tmpl-name"
use the following format for app template name "SAP <name> (<region>)"

2022-06-13 11:00 UTC, kaloyanspiridonov approved these changes

2022-06-13 11:00 UTC, merged

2022-06-13 16:17 UTC, PetarTodorovv commented
how/why this is merged with lots of failing tests and not approved PR - from access/process(OWNERS/CODEOWNERS) point of view and from functionality/code point of view?
<img width="931" alt="image" src="https://user-images.githubusercontent.com/31803034/173398586-0d42249e-5ae2-436a-b59c-bc6d1200bd16.png">