Subscription fixes
kyma-incubator/compass pull request #2451
Opened 2022-06-27 14:46 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-06-27 18:12 UTC, alextargov commented
/test all

2022-06-28 07:18 UTC, dzahariev commented on tests/ord-service/tests/subscription_flow_test.go
> +// for localEnv
Look like TODO left in code?

2022-06-28 07:18 UTC, dzahariev commented on tests/director/tests/application_templates_subscription_test.go
> +		appTemplateName := createAppTemplateName("app-template-name-subscription")
With e2e test the issue described above can be tested if you create more than one AppTemplate in the same region and verify that subscription is removed on unsubscribe, the expectation would be that the test will be unstable - will pass half of the times. To make it more unstable, you may create 10 or 20 templates in the same region as part of the test instead 2.

2022-06-28 07:20 UTC, alextargov commented on components/director/internal/domain/subscription/service.go
> +	filters := []*labelfilter.LabelFilter{
I think there should be only one template registered per region. @NickyMateev can you give a feedback here?

2022-06-28 08:23 UTC, NickyMateev commented on components/director/internal/domain/subscription/service.go
> +	filters := []*labelfilter.LabelFilter{
There's no use case where 1 SaaS app provider has multiple app templates registered in Compass for the same region.

However there's the use case where 2 SaaS app providers have registered their own single app template for one and the same region with Compass (they've onboarded with Compass essentially).

By the looks of the current label filter it looks to me that in such a use case the filter will return the templates for both SaaS app providers in that region, when we're only interested in one specifically (the one bound to the provider subaccount of the current request).

2022-06-29 07:41 UTC, dzahariev submitted a review, later dismissed

2022-06-29 11:08 UTC, PetarTodorovv requested changes

2022-06-29 11:08 UTC, PetarTodorovv commented on tests/director/tests/application_templates_subscription_test.go
> +func TestSubscriptionApplicationTemplateFlow(stdT *testing.T) {
That test only the "subscribe" scenario. Enhance a little bit the test at the end to make "unsubscribe" and to validate there is no application of the application template in the given tenant

2022-06-29 11:10 UTC, PetarTodorovv commented
Also, a gentle reminder to update the description of the PR. And maybe it's not a good idea to link our internal repository to the open-source project?

2022-06-29 13:25 UTC, PetarTodorovv commented on tests/director/tests/application_templates_subscription_test.go
> +	t.Run("Subscribe tenant to Application flow", func(t *testing.T) {
With the new approach, we made two subscriptions and have code duplication. We could either extract the subscribe logic as common and in the sub-tests to add the assertions or we could use the old setup just add the invoke the "unsubscribe" method - `BuildAndExecuteUnsubscribeRequest` and add assert that there is no application available

2022-06-29 14:06 UTC, dzahariev approved these changes

2022-06-29 14:14 UTC, PetarTodorovv approved these changes

2022-06-29 14:16 UTC, merged