Fix consumer provider ID in RuntimeContextSubscriptionFlows e2e test
kyma-incubator/compass pull request #2495
Opened 2022-07-19 11:51 UTC by la4ezar

**Description**
Fix consumer account ID in TestRuntimeContextSubscriptionFlows e2e-test. The consumer account ID was not adapted for a productive setup.

**Related issue(s)**

- [HOTFIX] https://github.com/kyma-incubator/compass/pull/2493

**Pull Request status**

- [ ] Implementation
- [ ] [N/A] Unit tests
- [ ] [N/A] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] [N/A] Mocks are regenerated, using the automated script

2022-07-19 13:11 UTC, DimitarPetrov approved these changes

2022-07-19 13:11 UTC, DimitarPetrov commented
/hold

2022-07-20 10:37 UTC, PetarTodorovv requested changes

2022-07-20 10:37 UTC, PetarTodorovv commented on tests/director/tests/runtime_contexts_api_test.go
> -		subscriptionConsumerSubaccountID := conf.TestConsumerSubaccountID // the parent is ApplicationsForRuntimeTenantName
I would suggest leaving the comment with the parent only to emphasize it is for the local setup.

2022-07-20 13:14 UTC, la4ezar commented
/retest

2022-07-21 07:44 UTC, DimitarPetrov approved these changes

2022-07-21 07:45 UTC, PetarTodorovv approved these changes

2022-07-21 07:46 UTC, merged