Destination fetcher service
kyma-incubator/compass pull request #2594
Opened 2022-08-30 13:21 UTC by georgifarashev

**Description**

Changes proposed in this pull request:
- Introduce destination fetcher component which reads destinations and maps them to consumption bundles.
- Consist of APIs and job running on only one pod

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2022-08-31 09:00 UTC, NickyMateev requested changes

2022-08-31 09:00 UTC, NickyMateev commented on components/director/internal/destinationfetchersvc/handler.go
> +	tenantID := request.Header.Get(h.config.InternalTenantIDHeaderName)
In the ORD Service don't pass this custom `InternalTenantId` header and instead pass `Tenant` header.

Then thanks to the current `internalClaims` id token configuration in combination with the authenticator middleware you will have the internal tenant id out of the box in the go context:

https://github.com/kyma-incubator/compass/blob/052949c0ef4304f7db818f5554056a8dc32c66b6/chart/compass/values.yaml#L446

https://github.com/kyma-incubator/compass/blob/052949c0ef4304f7db818f5554056a8dc32c66b6/components/director/internal/authenticator/claims/claims.go#L75

2022-08-31 13:10 UTC, NickyMateev commented
/test pre-main-compass-integration-no-dump

2022-08-31 14:35 UTC, NickyMateev commented
You get `Normal  BackOff  56s (x529 over 121m)  kubelet  Back-off pulling image "eu.gcr.io/kyma-project/incubator/compass-e2e-tests:PR-2594"` - are you sure that you had to bump the e2e tests, because there are none in this PR.

Either don't bump the e2e tests or put the PR number from the E2E test PR that you have, not this PR.

2022-09-01 09:03 UTC, nyordanoff approved these changes

2022-09-01 09:03 UTC, NickyMateev approved these changes

2022-09-01 09:19 UTC, StefanCholakov approved these changes

2022-09-01 09:21 UTC, merged