Enrich self register labels
kyma-incubator/compass pull request #2640
Opened 2022-09-20 08:08 UTC by PetarTodorovv

**Description**
Enrich the labels that we return during self-registration of runtimes

Changes proposed in this pull request:
- return the SaaS application name as part of the self-registered runtime's labels
- Make the new label immutable
- Adjust unit and E2E tests

**Related issue(s)**

- ...

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-09-20 08:48 UTC, DimitarPetrov commented on tests/director/tests/runtime_api_test.go
>  func TestRuntimeTypeImmutability(t *testing.T) {
Add assert that the new label is added to the self reg test as well.

2022-09-20 09:04 UTC, PetarTodorovv commented
/retest

2022-09-20 09:56 UTC, PetarTodorovv commented
/retest

2022-09-20 12:00 UTC, PetarTodorovv commented
/retest

2022-09-20 13:40 UTC, PetarTodorovv commented
/retest

2022-09-20 14:18 UTC, PetarTodorovv commented
/retest

2022-09-21 05:48 UTC, PetarTodorovv commented
/retest

2022-09-21 06:09 UTC, PetarTodorovv commented
/retest

2022-09-21 06:29 UTC, PetarTodorovv commented
/retest

2022-09-21 09:29 UTC, la4ezar requested changes

2022-09-21 09:29 UTC, la4ezar commented on components/director/pkg/config/selfreg_config.go
> +	c.RegionToSaaSAppName = make(map[string]string)
You can create this map with capacity = len(m).

2022-09-21 11:37 UTC, la4ezar approved these changes

2022-09-21 12:11 UTC, la4ezar approved these changes

2022-09-21 13:00 UTC, merged