Extend Webhook Output Template
kyma-incubator/compass pull request #2651
Opened 2022-09-27 09:29 UTC by la4ezar

**Description**
Extend the webhook output template to support configuration propagation.

Changes proposed in this pull request:
- Extend the webhook output template to support config, incomplete status code and actual status code
- Unit tests

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-09-27 10:50 UTC, la4ezar commented
/test pre-main-compass-integration

2022-09-28 06:53 UTC, StanislavStefanov submitted a review, later dismissed

2022-09-28 06:54 UTC, StanislavStefanov commented
/hold

2022-09-28 08:40 UTC, PetarTodorovv requested changes
Also, one general comment regarding the director version in the operations controller. Since we're updating something in the director's pkg ensure to update the inter deps as well.

2022-09-28 08:40 UTC, PetarTodorovv commented on components/director/pkg/webhook_client/client.go
> +	if *successStatusCode != resp.StatusCode && (incompleteStatusCode == nil || *incompleteStatusCode != resp.StatusCode) {
Instead of checking for nil here, there is a Validate method of the response and do the nil check there. And here check only the status codes.

2022-09-28 09:24 UTC, la4ezar commented on components/director/pkg/webhook_client/client.go
>  		errMsg += fmt.Sprintf("response success status code was not met - expected %d, got %d; ", *successStatusCode, resp.StatusCode)
After the changes:
If it is in the `Do` method - `response success status code was not met - expected success status code '202' or incomplete status code '204', got '500'`.
If it is in the `Poll` method - `response success status code was not met - expected success status code '200', got '500'`

2022-09-28 13:27 UTC, la4ezar commented
/test pre-main-compass-smoke-test

2022-09-28 14:03 UTC, dragobt approved these changes

2022-09-28 14:27 UTC, la4ezar commented
/retest

2022-09-28 15:15 UTC, la4ezar commented
/test pre-main-compass-integration

2022-09-28 15:42 UTC, merged