Formation assignments entity
kyma-incubator/compass pull request #2659
Opened 2022-09-29 15:07 UTC by PetarTodorovv

**Description**
Introducing a new formation assignment entity

Changes proposed in this pull request:
- new `formation_assignments` DB entity
- CRUD operations for repo and service layers 
- List formation assignments as part of the `formation` resolver
- data loaders for the new formation assignments resolver

**Pull Request status**
- [x] Implementation
- [x] Unit tests
- [x] [N/A] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2022-09-29 16:25 UTC, PetarTodorovv commented
/retest

2022-09-29 17:34 UTC, PetarTodorovv commented
/retest

2022-09-30 06:30 UTC, PetarTodorovv commented
/retest

2022-09-30 09:54 UTC, la4ezar requested changes

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formation/resolver.go
> +// FormationAssignmentService missing godoc
Add godoc.

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formation/resolver.go
> +// FormationAssignmentConverter missing godoc
Add godoc.

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formation/resolver.go
> +	err = tx.Commit()
if err := tx.Commit(); err != nil { ... }

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formation/resolver.go
> +// FormationAssignment missing godoc
Add godoc.

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formation/resolver.go
> +	err = tx.Commit()
if err := tx.Commit(); err != nil { ... }

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formationassignment/service.go
> +	err = s.repo.Update(ctx, in.ToModel(id, tenantID))
if err := ...; err != nil { ... }

2022-09-30 09:54 UTC, la4ezar commented on components/director/internal/domain/formationassignment/service.go
> +	log.C(ctx).Infof("Creating formation assignment with source: %q and source type: %q, and target: %q with target type: %q", in.Source, in.SourceType, in.Target, in.TargetType)
Maybe these types of logs will be helpful in the other functions too(Delete, Update, etc.).

2022-09-30 14:13 UTC, la4ezar approved these changes

2022-09-30 14:19 UTC, nyordanoff requested changes

2022-09-30 14:19 UTC, nyordanoff commented on components/director/internal/domain/formationassignment/repository_test.go
> +	suite.Run(t)
In all test suites there is a comment like: `// This test suite is not suitable for entities with embedded tenant in them.`

This, however, is outdated and misleading. Can I ask you to clean up those comments in the test suites.

2022-09-30 14:56 UTC, PetarTodorovv commented on components/director/internal/domain/formationassignment/converter.go
> +		return nil
If we return error we'll then need to check for error and if that's the case we need to return nil. This method is used in the resolver that returns `*graphql.FormationAssignment` and in the `MultipleToGraphQL` method that also return `[]*graphql.FormationAssignment`. That's why here I directly return nil(and ignore the marshal error)

2022-10-03 06:38 UTC, PetarTodorovv commented
/retest

2022-10-03 10:03 UTC, nyordanoff approved these changes

2022-10-03 10:36 UTC, merged