Keep track of formation assignments
kyma-incubator/compass pull request #2665
Opened 2022-09-30 12:34 UTC by StanislavStefanov

**Description**

Changes proposed in this pull request:
- Create formationAssignments when assigning to formation
- Delete formationAssignments when unassigning from formation

**Pull Request status**
- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-10-06 13:33 UTC, StanislavStefanov commented
/test pre-main-compass-integration-no-dump

2022-10-06 16:42 UTC, ivantenevvasilev commented
/test pre-main-compass-gke-benchmark

2022-10-12 09:04 UTC, PetarTodorovv requested changes

2022-10-12 09:19 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/service.go
> +func (s *service) ListFormationAssignmentsForObject(ctx context.Context, formationID, objectID string) ([]*model.FormationAssignment, error) {
We are not listing the assignments by their id rather we are looking for assignment which have their source property set to ObjectID or their target property set to ObjectID. For example if we have an application that is part of the formation we want to find the assignments in which the application takes part. So we need to find all of the assignments for which the application is source and all of the assignments for which the application is target.

2022-10-12 09:28 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/service.go
> +	}
This part is refactored in the next PR. There we pass the notification and it is clear whether we have notification or no.

2022-10-12 09:34 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/service.go
> +	if response != nil && response.IncompleteStatusCode != nil && *response.ActualStatusCode == *response.IncompleteStatusCode {
This is already refactored in the next PR

2022-10-12 09:36 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/service.go
> +	if _, err := s.Create(ctx, s.formationAssignmentConverter.ToInput(assignment)); err != nil {
It was preparation for the nex PR. We have already adapted it there.

2022-10-12 09:58 UTC, StanislavStefanov commented on components/director/internal/repo/list.go
> +// ListConditionTree lists tenant scoped entities with tenant isolation subquery based on equal condition on tenantColumn.
The doc may be a bit missleading. This method only works for entities with embeded tenant. So the tenant isolation is done by equal condition for the tenant column. Will remove the word subquery from the doc

2022-10-12 09:58 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/repository.go
> +	var entitiesWithTargetObjectID EntityCollection
It is leftover. We have already removed it in the next PR

2022-10-12 13:38 UTC, StanislavStefanov commented on components/director/internal/domain/formationassignment/service.go
> +	if response != nil && response.Error != nil && *response.Error != "" {
Such cases are handled by the webhook client. If the response status code does not match successStatusCode or incompleteStatus code the webhook client will return error

2022-10-13 06:58 UTC, PetarTodorovv commented
/retest

2022-10-13 06:58 UTC, PetarTodorovv approved these changes

2022-10-14 05:00 UTC, dzahariev commented on components/director/internal/model/formation_assignment.go
> +	InitialAssignmentState FormationAssignmentState = "INITIAL"
Ir will be easier for maintenance if the constant names use the following naming schema:
<Object><State>
In this case names to be:
AssignmentStateInitial
AssignmentStateReady
AssignmentStateConfigPending
...
As when you want to reference the object state in code will use autocomplete to look for the object and will see the states that are applicable for this object.

2022-10-14 05:02 UTC, dzahariev approved these changes
I had usability related comment that is not a blocker for merge.

2022-10-14 06:36 UTC, alextargov commented on components/director/internal/domain/runtime_context/repository.go
> +		query := fmt.Sprintf(`$[*] ? (@ == "%s")`, scenarioValue)
We can extract this common query that is being used in a couple of places. It's a suggestion, not mandatory.

2022-10-14 10:00 UTC, desislavaa approved these changes

2022-10-14 11:25 UTC, ivantenevvasilev commented
/retest

2022-10-14 11:27 UTC, ivantenevvasilev commented
/test pull-tests-build

2022-10-14 12:49 UTC, ivantenevvasilev commented
/test pull-pairing-adapter-build

2022-10-14 13:01 UTC, ivantenevvasilev commented
/retest pre-main-compass-integration-with-dump

2022-10-14 13:03 UTC, ivantenevvasilev commented
/test pre-main-compass-integration-with-dump

2022-10-14 13:16 UTC, PetarTodorovv approved these changes

2022-10-14 13:45 UTC, ivantenevvasilev commented
/retest

2022-10-14 14:11 UTC, ivantenevvasilev commented
/retest

2022-10-14 15:06 UTC, ivantenevvasilev commented
/test pull-tests-build

2022-10-14 15:58 UTC, ivantenevvasilev commented
/retest

2022-10-14 16:07 UTC, merged