Support atom tenant types
kyma-incubator/compass pull request #2698
Opened 2022-10-17 14:01 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2022-10-17 14:07 UTC, kaloyanspiridonov requested changes

2022-10-17 14:07 UTC, kaloyanspiridonov commented on components/director/pkg/tenant/entity.go
> +	// Organization tenants can be parents of Folder tenants.
// Organization tenants can be parents of Folder tenants. ->  // Organization tenants can be parents of Folder or ResourceGroup tenants.

2022-10-17 14:07 UTC, kaloyanspiridonov commented on components/director/pkg/tenant/entity.go
> +	// ResourceGroup tenants must have a parent of type Folder.
// ResourceGroup tenants must have a parent of type Folder. -> // ResourceGroup tenants must have a parent of type Folder or organization.

2022-10-18 07:21 UTC, alextargov commented
/test all

2022-10-19 11:46 UTC, la4ezar approved these changes

2022-10-19 11:55 UTC, kaloyanspiridonov approved these changes

2022-10-19 12:35 UTC, alextargov commented
/retest

2022-10-19 13:05 UTC, merged