Bump vulnerable dependencies
kyma-incubator/compass pull request #2740
Opened 2022-11-15 12:26 UTC by NickyMateev

# Bump vulnerable dependencies

**Description**

Changes proposed in this pull request:
- bump k8s.io/apimachinery 0.25.0 -> 0.25.1

2022-11-15 12:53 UTC, NickyMateev commented
/retest

2022-11-16 11:14 UTC, NickyMateev commented
/test pull-operations-controller-build

2022-11-16 11:15 UTC, NickyMateev commented
/test 
pull-hydrator-build

2022-11-16 11:15 UTC, NickyMateev commented
/test pull-hydrator-build

2022-11-16 11:15 UTC, NickyMateev commented
/test pull-external-services-mock-build

2022-11-16 11:34 UTC, NickyMateev commented
/test pull-system-broker-build

2022-11-16 11:34 UTC, NickyMateev commented
/test pull-pairing-adapter-build

2022-11-16 11:35 UTC, NickyMateev commented
/test pull-operations-controller-build

2022-11-16 11:35 UTC, NickyMateev commented
/test pull-external-services-mock-build

2022-11-16 11:37 UTC, NickyMateev commented
/test pull-system-broker-build

2022-11-16 11:37 UTC, NickyMateev commented
/test pull-pairing-adapter-build

2022-11-16 11:47 UTC, NickyMateev commented
/retest

2022-11-16 13:33 UTC, dzahariev requested changes
Increase also compass-external-services-mock in values.yaml

2022-11-16 13:39 UTC, NickyMateev commented
> Increase also compass-external-services-mock in values.yaml

Good catch - fixed 👍

2022-11-16 13:39 UTC, dzahariev approved these changes

2022-11-17 13:47 UTC, dzahariev approved these changes

2022-11-17 13:49 UTC, PetarTodorovv approved these changes

2022-11-17 14:24 UTC, merged