Support SaaS application tenants consumable via BTP service instances
kyma-incubator/compass pull request #2841
Opened 2023-01-26 18:45 UTC by kaloyanspiridonov

**Description**

Changes proposed in this pull request:
- Introduce instances label

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-01-26 22:36 UTC, kaloyanspiridonov commented
/retest

2023-01-26 22:40 UTC, kaloyanspiridonov commented
/retest

2023-01-27 16:04 UTC, kaloyanspiridonov commented
/retest

2023-01-29 17:23 UTC, kaloyanspiridonov commented
/test pre-main-compass-schema-migrator-validate

2023-01-30 07:18 UTC, PetarTodorovv requested changes

2023-01-30 11:41 UTC, kaloyanspiridonov commented on components/director/internal/domain/subscription/service.go
> +	instances, ok := instancesLabel.Value.(float64)
When you retrieve the label value from the DB, it's of type float64 - more info https://pkg.go.dev/encoding/json#Unmarshal

2023-01-30 14:20 UTC, kaloyanspiridonov commented
/test pre-main-compass-integration-with-dump

2023-01-30 14:35 UTC, kaloyanspiridonov commented
/test pre-main-compass-gke-benchmark

2023-01-30 15:53 UTC, PetarTodorovv commented on tests/director/tests/runtime_contexts_api_test.go
> +		instancesLabel, ok := consumerSubaccountRuntime.RuntimeContexts.Data[0].Labels["instances"].(float64)
`subscription.InstancesLabelKey` instead of "instances"?

2023-01-30 15:53 UTC, PetarTodorovv commented on tests/director/tests/runtime_contexts_api_test.go
> +		instancesLabel, ok = consumerSubaccountRuntime.RuntimeContexts.Data[0].Labels["instances"].(float64)
something very minor: `subscription.InstancesLabelKey` instead of "instances"? below as well

2023-01-30 15:58 UTC, NickyMateev submitted a review, later dismissed

2023-01-31 07:23 UTC, PetarTodorovv approved these changes

2023-01-31 07:25 UTC, merged