Support arbitrary parameters in spii
kyma-incubator/compass pull request #2869
Opened 2023-02-06 13:46 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-02-07 09:21 UTC, alextargov commented
/retest

2023-02-07 09:29 UTC, alextargov commented
reset-vm

2023-02-07 09:30 UTC, alextargov commented
/retest

2023-02-09 09:40 UTC, kaloyanspiridonov requested changes

2023-02-09 09:40 UTC, kaloyanspiridonov commented on components/director/pkg/graphql/graphqlizer/graphqlizer.go
>  		{{- end }}
update director dependency in all projects

2023-02-09 10:03 UTC, alextargov commented
/retest

2023-02-09 11:41 UTC, kaloyanspiridonov approved these changes

2023-02-09 14:15 UTC, la4ezar approved these changes

2023-02-09 14:18 UTC, merged