ORD Aggregation of C4C CNS fails with local tenant id is required
kyma-incubator/compass pull request #2872
Opened 2023-02-07 13:45 UTC by dragobt

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-02-07 14:02 UTC, dragobt commented
/retest

2023-02-07 15:22 UTC, dragobt commented
/retest

2023-02-08 05:17 UTC, dragobt commented
/retest

2023-02-08 16:48 UTC, dragobt commented
/retest

2023-02-09 14:18 UTC, la4ezar requested changes

2023-02-09 14:18 UTC, la4ezar commented on chart/compass/values.yaml
> -      version: "PR-2868"
Update the versions of all other components, because you've changed the go.sum/mod files.

2023-02-09 15:10 UTC, dragobt commented
/retest

2023-02-09 15:13 UTC, la4ezar submitted a review, later dismissed

2023-02-10 06:56 UTC, alextargov approved these changes

2023-02-10 06:58 UTC, dragobt commented
/retest

2023-02-10 07:01 UTC, la4ezar approved these changes

2023-02-10 07:59 UTC, merged