Fail when deleting Application if it is part of formation
kyma-incubator/compass pull request #2884
Opened 2023-02-15 13:55 UTC by StanislavStefanov

Changes proposed in this pull request:
- Fail when deleting Application if it is part of formation. Otherwise if the application is deleted while still being part of formation formation assignments for that app are left orphaned

**Pull Request status**

- [X] Implementation
- [X] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated

2023-02-16 10:26 UTC, kaloyanspiridonov requested changes

2023-02-16 10:26 UTC, kaloyanspiridonov commented on components/director/internal/domain/application/service.go
> +		msg := fmt.Sprintf("System %s is still used and cannot be deleted. Unassign the system from the following formations first: %s.", application.Name, strings.Join(scenarios, ", "))
Use generic message. We will reuse this method to prevent merge of systems  if there are existing formations associated with the source system

2023-02-16 14:46 UTC, StanislavStefanov commented
/retest

2023-02-16 16:16 UTC, StanislavStefanov commented
reset-vm

2023-02-16 16:25 UTC, StanislavStefanov commented
/retest

2023-02-17 06:55 UTC, StanislavStefanov commented
reset-vm

2023-02-17 08:36 UTC, StanislavStefanov commented
reset-vm

2023-02-17 10:33 UTC, StanislavStefanov commented
reset-vm

2023-02-17 10:34 UTC, StanislavStefanov commented
/retest

2023-02-22 08:06 UTC, ivantenevvasilev approved these changes

2023-02-22 08:11 UTC, StanislavStefanov commented
/retest

2023-02-22 08:11 UTC, StanislavStefanov commented
/retest

2023-02-22 12:55 UTC, ivantenevvasilev submitted a review, later dismissed

2023-02-22 13:37 UTC, kaloyanspiridonov commented on tests/director/tests/application_api_test.go
>  		t.Logf("Unassigning src-app from formation %s", newFormation)
fix the log message

2023-02-22 14:05 UTC, ivantenevvasilev approved these changes

2023-02-22 14:50 UTC, merged