Allow specifying optional application namespace property in Third Party systems registration
kyma-incubator/compass pull request #2893
Opened 2023-02-20 10:04 UTC by emmakarova

**Description**

Added Optional field for the placeholders when registering application from template

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-02-22 09:15 UTC, emmakarova commented
/test pull-director-build

2023-02-22 09:18 UTC, emmakarova commented
/retest

2023-02-22 09:40 UTC, dzahariev requested changes

2023-02-22 09:40 UTC, dzahariev commented on chart/compass/values.yaml
> -      version: "PR-2898"
Bump also tests version

2023-02-24 06:07 UTC, emmakarova commented
Replaced by https://github.com/kyma-incubator/compass/pull/2907

2023-02-24 06:07 UTC, closed without merging