Bump alpine to 3.17.2
kyma-incubator/compass pull request #2897
Opened 2023-02-21 08:20 UTC by ivantenevvasilev

**Description**

Changes proposed in this pull request:
- bump alpine from `3.17.1` to `3.17.2`

**Related issue(s)**
- #2868

**Pull Request status**

- [x] [N/A] Implementation
- [x] [N/A] Unit tests
- [x] [N/A] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [x] [N/A] Mocks are regenerated, using the automated script

2023-02-21 14:25 UTC, ivantenevvasilev commented
/test pre-main-compass-integration-no-dump

2023-02-21 14:32 UTC, dzahariev requested changes

2023-02-21 14:32 UTC, dzahariev commented on chart/compass/values.yaml
>        containerRegistry:
Bump also external services mock version.

2023-02-21 14:42 UTC, dzahariev approved these changes

2023-02-21 14:46 UTC, ivantenevvasilev commented
/retest

2023-02-21 14:51 UTC, dzahariev commented
/retest

2023-02-21 15:19 UTC, nyordanoff submitted a review, later dismissed

2023-02-22 07:51 UTC, ivantenevvasilev commented
/test pre-main-compass-integration-no-dump

2023-02-22 09:09 UTC, dzahariev approved these changes

2023-02-22 09:34 UTC, StanislavStefanov approved these changes

2023-02-22 09:35 UTC, merged