Add mutations for tenant access create and delete
kyma-incubator/compass pull request #2953
Opened 2023-03-16 11:30 UTC by StanislavStefanov

**Description**

Changes proposed in this pull request:
- Introduce addTenantAccess mutation
- Introduce removeTenantAccess mutation
 
**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2023-03-17 10:43 UTC, StanislavStefanov commented
/retest

2023-03-17 12:10 UTC, StanislavStefanov commented
reset-vm

2023-03-17 12:12 UTC, StanislavStefanov commented
/retest

2023-03-17 12:44 UTC, StanislavStefanov commented
/retest

2023-03-20 06:57 UTC, PetarTodorovv requested changes

2023-03-20 08:02 UTC, StanislavStefanov commented on components/director/internal/repo/tenant_access_m2m.go
> +			DELETE FROM %s WHERE %s AND tenant_id IN (SELECT id FROM parents)`
This makes it imposible to delete records with access false. Also I have not faoud any reason to delete only the records with access true.

2023-03-20 09:46 UTC, StanislavStefanov commented on components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
regenerated them with the correct version

2023-03-20 10:37 UTC, PetarTodorovv approved these changes

2023-03-20 11:55 UTC, nkanchev approved these changes

2023-03-20 12:58 UTC, merged