Taking the formation lifecycle notification status in the overall formation status
kyma-incubator/compass pull request #2955
Opened 2023-03-16 15:44 UTC by la4ezar

**Description**
In previous PR we introduced synchronous formation lifecycle notifications and state and error fields to the formation. In this PR we are taking this state and error fields into account when calculating the overall status of the formation in the status sub-resolver.

Changes proposed in this pull request:
- Taking this state and error fields into account when calculating the overall status of the formation in the status sub-resolver.
- Unit tests.
- Adapt the existing e2e tests.

**Related issue(s)**

- https://github.com/kyma-incubator/compass/pull/2876

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2023-03-17 07:27 UTC, la4ezar commented
/retest

2023-03-20 07:40 UTC, la4ezar commented
/retest

2023-03-20 08:47 UTC, la4ezar commented
/retest

2023-03-21 10:09 UTC, StanislavStefanov requested changes

2023-03-21 10:15 UTC, la4ezar commented on tests/director/tests/formation_api_test.go
> +				// The aggregated formation status is IN_PROGRESS because of the FAs, but the Formation state should be READY
Currently, we don't have a setup to add a test like this and it will consume a lot of time to set it up. We will add such a test in the future.

2023-03-21 13:13 UTC, la4ezar commented
/retest

2023-03-21 13:42 UTC, la4ezar commented
/retest

2023-03-21 14:09 UTC, la4ezar commented
/retest

2023-03-21 15:14 UTC, merged