Kyma adapter
kyma-incubator/compass pull request #3090
Opened 2023-05-30 12:22 UTC by StanislavStefanov

**Description**

Changes proposed in this pull request:
- add charts for kyma adapter component
- add kyma adapter skeleton

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2023-05-31 11:58 UTC, StanislavStefanov commented
/test pre-main-compass-integration-with-dump

2023-05-31 13:33 UTC, StanislavStefanov commented
reset-vm

2023-05-31 13:36 UTC, StanislavStefanov commented
/test pre-main-compass-integration-with-dump

2023-06-02 08:22 UTC, PetarTodorovv requested changes

2023-06-02 08:22 UTC, PetarTodorovv commented on components/kyma-adapter/internal/claims-validator/validate.go
> +type ClaimsValidator struct{}
Check the comment for the package/import/structure renaming

2023-06-02 08:22 UTC, PetarTodorovv commented on components/kyma-adapter/internal/handler/handler.go
> +	GqlClient *graphql.Client
`directorGQLClient`? or something similar?

2023-06-02 11:15 UTC, StanislavStefanov commented on components/director/pkg/auth-middleware/middleware.go
> +			ctx = tokenClaims.ContextWithClaimsAndProviderTenant(ctx)
For this flow the provider and consumer tenant should be the same. The cert_service context provider should be matched which will provide the providerTenant. No other context providers are expected to match in the productive scenarios. When the tenant object map does not contain entries for consumer they will be created with the same values as the entries for the provider. As the two values are equal we can use either of them.

In the local scenarios the certificates used in the tests are whitelisted which causes second object context provider to be matched. The second object context provider provides empty values for the consumer tenant. As there are entries in the map the provider values are not duplicated in the consumer values regardless of them being empty. In that case the consumer tenant that reaches us in the context is empty and the request validation fails. The provider tenant on the other side is correctly populated.

For both productive and local setup the provider tenant will do the work.

2023-06-02 11:41 UTC, StanislavStefanov commented on chart/compass/charts/kyma-adapter/values.yaml
> +  maxReplicas: 2
I am not sure if there is need for that. The only reason I added the configuration is that if the min and max replicas are equal we will be receiving alerts for running at max replicas

2023-06-02 12:18 UTC, StanislavStefanov commented on chart/compass/charts/kyma-adapter/templates/deployment.yaml
> +              path: "healthz"
The healthz endpoint is on the main router and the productive handler is on a subrouter with path prefix kyma-adapter.

2023-06-05 06:55 UTC, PetarTodorovv commented on chart/compass/charts/kyma-adapter/values.yaml
> +  maxReplicas: 2
hm, maybe it's okay to have productive overrides - min/max replicas due to high availability, also resources limits/request, istio resources overrides?

2023-06-05 07:08 UTC, PetarTodorovv approved these changes

2023-06-05 07:49 UTC, StanislavStefanov commented
/hold

2023-06-05 08:12 UTC, dzahariev submitted a review, later dismissed

2023-06-09 14:06 UTC, StanislavStefanov commented
/retest

2023-06-09 14:32 UTC, dzahariev approved these changes

2023-06-09 14:32 UTC, StanislavStefanov commented
/hold cancel

2023-06-09 14:57 UTC, PetarTodorovv approved these changes

2023-06-09 14:58 UTC, merged