Introduce resolvers for api event
kyma-incubator/compass pull request #3144
Opened 2023-06-26 10:48 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-06-26 12:27 UTC, alextargov commented
/retest

2023-06-26 13:29 UTC, dzahariev commented on components/connectivity-adapter/go.sum
> +github.com/kyma-incubator/compass/components/director v0.0.0-20230626120331-7d3f35c39b0d h1:1ni3udpgzH4eZcNXUhQPxkO0zA3frlKS4IHo+o3A1sg=
go mod tidy

2023-06-26 13:41 UTC, dzahariev requested changes
Looks good.
Run `go mod tidy` to all components to cleanup the go sum files from old dependencies before we merge this.

2023-06-26 16:58 UTC, alextargov commented
/retest

2023-06-26 18:20 UTC, dzahariev approved these changes

2023-06-27 05:59 UTC, PetarTodorovv approved these changes

2023-06-27 05:59 UTC, merged