Production ready s4 proxy
kyma-incubator/compass pull request #3180
Opened 2023-07-27 12:22 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-08-09 05:33 UTC, alextargov commented
/retest

2023-08-09 07:30 UTC, alextargov commented
/retest

2023-08-09 08:28 UTC, alextargov commented
/retest

2023-08-09 09:01 UTC, alextargov commented
/retest

2023-08-09 12:39 UTC, alextargov commented
/retest

2023-08-09 12:41 UTC, alextargov commented
/retest

2023-08-10 08:15 UTC, kaloyanspiridonov requested changes

2023-08-10 08:15 UTC, kaloyanspiridonov commented on components/director/internal/open_resource_discovery/service.go
> +		ordRequestObject.Headers = headers
i prefer appending of headers instead of overriding

2023-08-10 09:05 UTC, alextargov commented on components/director/internal/domain/webhook/entity.go
> +	ProxyURL              sql.NullString `db:"proxy_url"`
We will need this, yes. When this go to dev, we should execute a one time SQL script to populate this column.

2023-08-10 09:06 UTC, alextargov commented on installation/resources/compass-overrides-local.yaml
> +    ordWebhookMappings: '[{ "OrdUrlPath": "/.well-known/open-resource-discovery", "Type": "SAP temp1", "PpmsProductVersions": ["12345"], "SubdomainSuffix": "" }, { "ProxyURL": "http://compass-externa
We can, but this is mainly for the e2e tests executed locally.

2023-08-10 09:18 UTC, alextargov commented on tests/ord-aggregator/tests/handler_test.go
> +	//basicORDConfigSecurity := &fixtures.ORDConfigSecurity{
Oops

2023-08-10 12:13 UTC, alextargov commented
/retest

2023-08-10 12:21 UTC, kaloyanspiridonov submitted a review, later dismissed

2023-08-10 12:23 UTC, alextargov commented
/retest

2023-08-11 10:25 UTC, alextargov commented
/retest

2023-08-11 10:25 UTC, NickyMateev commented
/retest

2023-08-11 10:44 UTC, NickyMateev approved these changes

2023-08-11 11:43 UTC, alextargov commented
/hold

2023-08-11 11:50 UTC, alextargov commented
/retest

2023-08-14 07:12 UTC, NickyMateev approved these changes

2023-08-14 07:15 UTC, merged