Get app by local tenant id and app template id
kyma-incubator/compass pull request #3198
Opened 2023-08-07 15:27 UTC by yordanovagabriela

**Description**

Changes proposed in this pull request:
- Introduce a new graphql request to get application by local tenant id and app template id

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-08-08 10:48 UTC, kaloyanspiridonov requested changes

2023-08-08 10:48 UTC, kaloyanspiridonov commented on chart/compass/charts/director/config.yaml
> +    applicationByLocalTenantIDAndAppTemplateID: ["application:read"]
add to director/hack/config-local.yaml as well

2023-08-08 10:48 UTC, kaloyanspiridonov commented on components/director/internal/domain/root_resolver.go
> +func (r *queryResolver) ApplicationByLocalTenantIDAndAppTemplateID(ctx context.Context, localTenantID, appTemplateID string) (*graphql.Application, error) {
missing e2e tests

2023-08-09 12:29 UTC, yordanovagabriela commented
/test pre-main-compass-integration-no-dump

2023-08-09 13:08 UTC, yordanovagabriela commented
/test pre-main-compass-gke-benchmark

2023-08-09 13:21 UTC, yordanovagabriela commented
/test pre-main-compass-gke-benchmark

2023-08-09 13:31 UTC, yordanovagabriela commented
/test pre-main-compass-gke-benchmark

2023-08-10 06:49 UTC, yordanovagabriela commented
/test pull-director-build

2023-08-10 06:49 UTC, kaloyanspiridonov requested changes

2023-08-10 06:49 UTC, kaloyanspiridonov commented on components/director/hack/config-local.yaml
> +    - "applicationByLocalTenantIDAndAppTemplateID:read"
You are not introducing new scope. You should add "applicationByLocalTenantIDAndAppTemplateID: ["application:read"]" in the query section

2023-08-10 07:01 UTC, kaloyanspiridonov approved these changes

2023-08-10 07:18 UTC, yordanovagabriela commented
/test pre-main-compass-smoke-test

2023-08-10 09:27 UTC, yordanovagabriela commented
/test pre-main-compass-integration-with-dump

2023-08-10 13:24 UTC, ekaterina-mitova approved these changes
Looks good to me.

2023-08-10 13:26 UTC, merged