FA not present when updation status
kyma-incubator/compass pull request #3239
Opened 2023-08-21 06:54 UTC by StanislavStefanov

**Description**

If we have async TM notification receiver, when we notify them, they may be faster to report status than the transaction that created the respective assignment.

This will result in a status report before the assignments are persisted and commited in the DB. Then the status API will not see such assignment and will fail with Not Found.

Changes proposed in this pull request:
- persist FAs before processing the notifications
- delete the persisted resources in case the forrmation assignment has failed after ther persisting

**Pull Request status**

- [X] Implementation
- [X] Unit tests
- [X] `chart/compass/values.yaml` is updated

2023-08-25 12:17 UTC, PetarTodorovv requested changes

2023-08-25 12:17 UTC, PetarTodorovv commented on components/director/internal/domain/formation/service.go
> +		// Execute W1, then execute W2. W2 takes for example 10 seconds. Before the W2 processing finishes a FA status update request for W1 is received.
```
// Example: Participant 1(P1) has ASYNC webhook(W1) and Participant2(P2) has SYNC webhook(W2). Assign both P1 and P2 to a formation.
// Formation assignments are generated.
// Execute W1, then execute W2. W2 takes, for example, 10 seconds. Before the W2 processing finishes, an FA status update request for W1 is received.
// When fetching the corresponding FA from the DB we get an object not found error, as the status update is performed in new transaction and the transaction in which the FA were generated is still running.
```
?

2023-08-25 12:17 UTC, PetarTodorovv commented on components/director/internal/domain/formation/service.go
> +		// transaction. The leftover resources should be deleted separately.
```
// If the assigning of the object fails, the transaction opened in the resolver will be rolled back.
// The FA records and the labels for the object will not be reverted as they were persisted as part of another
// transaction. The leftover resources should be deleted separately.
```

2023-08-25 12:17 UTC, PetarTodorovv commented on components/director/internal/domain/formation/service.go
One general question - do we need an E2E test for this scenario? E.g. "async" handler in the ext-svc-mock that doesn't have a delay but rather immediately executes "FA status update request" to the status API, opposite to what we have now in the async handler with the fixed time delay.

2023-08-28 06:52 UTC, StanislavStefanov commented on components/director/internal/domain/formation/service.go
> +		// received before the FA is persisted in the database.
It is unlikely as the async implementations respond with accepted and then perform their logic. The issue is the big delay when processing the syncronous notification that provides the ASYNC participant to process its notification and to respond

2023-08-28 07:30 UTC, StanislavStefanov commented on components/director/internal/domain/formation/service.go
I dont think that we need as this is kind of a corner case

2023-08-28 08:34 UTC, PetarTodorovv submitted a review, later dismissed

2023-08-28 09:13 UTC, PetarTodorovv approved these changes

2023-08-28 10:11 UTC, StanislavStefanov commented
/retest

2023-08-28 11:06 UTC, merged