[WIP] Kyma 2.9.3
kyma-incubator/compass pull request #3397
Opened 2023-10-13 11:58 UTC by ognyvrac

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-10-16 06:40 UTC, ognyvrac commented
/test pre-main-compass-integration-with-dump

2023-10-17 07:20 UTC, ekaterina-mitova commented on docs/compass/04-01-installation.md
> +You must have a Kyma installation with an enabled Runtime Agent. For more information, see [Enable Kyma with Runtime Agent](https://github.com/kyma-project/kyma/blob/2.9.3/docs/04-operation-guides/op
with enabled Runtime Agent

2023-10-17 09:46 UTC, ekaterina-mitova submitted a review, later dismissed
Looks good to me!

2023-10-18 06:59 UTC, ognyvrac commented
/hold

2023-10-19 08:49 UTC, PetarTodorovv requested changes

2023-10-19 08:49 UTC, PetarTodorovv commented on chart/compass/charts/prometheus-postgres-exporter/values.yaml
> -  pspEnabled: true
There is also an .md file referring to that value - `compass/chart/compass/charts/prometheus-postgres-exporter/README.md` we can remove it from there as well

2023-10-19 08:49 UTC, PetarTodorovv commented on chart/ory/templates/psp.yaml
> -{{- if .Values.maintenance.podSecurityPolicy.enabled }}
We removed the file but seems we still have the chart configuration `maintenance -> podSecurityPolicy`?

2023-10-19 15:06 UTC, PetarTodorovv approved these changes

2023-10-20 07:36 UTC, PetarTodorovv approved these changes

2023-10-20 12:08 UTC, ognyvrac commented
/unhold

2023-10-20 12:26 UTC, PetarTodorovv approved these changes

2023-10-20 12:26 UTC, ognyvrac commented
/hold

2023-10-20 13:00 UTC, ekaterina-mitova approved these changes
Looks good to me.

2023-10-20 13:02 UTC, ognyvrac commented
/unhold

2023-10-20 13:49 UTC, ognyvrac commented
/retest pre-main-compass-integration-no-dump

2023-10-20 13:50 UTC, ognyvrac commented
/test pre-main-compass-integration-no-dump

2023-10-20 14:12 UTC, merged