Forbid self reg lbl at non cert flow
kyma-incubator/compass pull request #3403
Opened 2023-10-19 07:13 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-10-19 08:10 UTC, alextargov commented
/retest

2023-10-23 14:18 UTC, StanislavStefanov requested changes

2023-10-23 14:18 UTC, StanislavStefanov commented on chart/compass/values.yaml
> +      version: "PR-3303"
3403

2023-10-23 18:25 UTC, alextargov commented
/retest

2023-10-24 06:07 UTC, StanislavStefanov approved these changes

2023-10-24 06:19 UTC, kaloyanspiridonov approved these changes

2023-10-24 06:19 UTC, merged