Add create update timestamp on app template
kyma-incubator/compass pull request #3404
Opened 2023-10-19 12:33 UTC by alextargov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-10-19 13:31 UTC, la4ezar submitted a review, later dismissed

2023-10-19 13:51 UTC, dragobt requested changes

2023-10-19 13:51 UTC, dragobt commented on chart/compass/values.yaml
bump schema-migrator version

2023-10-19 13:57 UTC, dragobt commented on components/director/hack/jwt_generator.sh
> +    local PAYLOAD=$(echo "{ \"scopes\": \"webhook:write formation_template.webhooks:read runtime.webhooks:read application_template.labels:write application.local_tenant_id:write tenant_subscription:
why do we add `application_template.labels:write`? I think it is already present - it is the 4th scope

2023-10-19 14:54 UTC, dragobt approved these changes

2023-10-19 15:29 UTC, alextargov commented
/retest

2023-10-20 06:45 UTC, dragobt approved these changes

2023-10-20 07:01 UTC, StanislavStefanov approved these changes

2023-10-20 07:02 UTC, merged