[WIP] Return null config instead of empty string
kyma-incubator/compass pull request #3434
Opened 2023-11-01 16:09 UTC by ivantenevvasilev

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-11-02 07:30 UTC, ivantenevvasilev commented
/test pre-main-compass-integration-with-dump

2023-11-02 09:37 UTC, ivantenevvasilev commented
/test pre-main-compass-integration-with-dump

2023-11-02 09:40 UTC, PetarTodorovv requested changes

2023-11-02 09:40 UTC, PetarTodorovv commented on components/director/pkg/webhook/types.go
> +	resBytes = bytes.ReplaceAll(resBytes, []byte("<nil>"), []byte("null"))
Could you please add two comments for both replace scenarios? E.g. the first one is when the field in the go code is a pointer(nil/empty) and we have explicit quotes in the templates resulting in the `"<nil>"` but the second case is when we don't have quotes in the template and we have only `<nil>`?

2023-11-02 09:40 UTC, PetarTodorovv commented on components/director/pkg/webhook/types.go
And one general comment - we need to verify all of the components/adapters that we have are not affected by this change, i.e. in the new setup I think they should have only a not nil check? Rather than before not nil check + additional non empty string checks - "{}", "null", etc..

2023-11-02 13:28 UTC, PetarTodorovv submitted a review, later dismissed

2023-11-02 14:37 UTC, PetarTodorovv approved these changes

2023-11-02 16:08 UTC, PetarTodorovv approved these changes

2023-11-03 08:03 UTC, alextargov approved these changes

2023-11-03 10:43 UTC, PetarTodorovv approved these changes

2023-11-03 10:55 UTC, alextargov approved these changes

2023-11-03 11:03 UTC, merged