Adopt ORD 1.8.1
kyma-incubator/compass pull request #3448
Opened 2023-11-08 08:55 UTC by dzahariev

**Description**

Changes proposed in this pull request:
- Add runtimeRestriction to packages

**Related issue(s)**
- ...

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-12-21 14:42 UTC, emmakarova commented
/retest

2023-12-21 14:46 UTC, emmakarova commented
/retest

2023-12-21 15:02 UTC, emmakarova commented
/retest

2023-12-22 07:58 UTC, emmakarova commented
/retest

2023-12-22 09:17 UTC, emmakarova commented
/retest

2023-12-22 09:33 UTC, emmakarova commented
/retest

2023-12-22 09:40 UTC, emmakarova commented
/retest

2023-12-22 09:44 UTC, emmakarova commented
/retest

2024-01-02 07:08 UTC, emmakarova commented
/retest

2024-01-02 08:07 UTC, emmakarova commented
/test all

2024-01-02 08:12 UTC, emmakarova commented
/test all

2024-01-02 09:05 UTC, emmakarova commented
/retest

2024-01-02 10:58 UTC, emmakarova commented
/retest

2024-01-02 13:46 UTC, dragobt requested changes

2024-01-02 14:55 UTC, dragobt submitted a review, later dismissed

2024-01-03 08:00 UTC, nyordanoff requested changes

2024-01-03 08:00 UTC, nyordanoff commented on components/schema-migrator/migrations/director/20231219121259_introduce-data-products.up.sql
> +BEGIN;
Rename both migrations because new ones with bigger timestamp (`20231228152252`) than yours were merged into main.

2024-01-03 08:51 UTC, emmakarova commented
/test all

2024-01-03 09:51 UTC, nyordanoff approved these changes

2024-01-03 09:51 UTC, emmakarova commented
/retest

2024-01-03 10:50 UTC, emmakarova commented
/retest

2024-01-03 10:55 UTC, alextargov approved these changes

2024-01-03 11:38 UTC, emmakarova commented
/retest

2024-01-03 11:51 UTC, nyordanoff approved these changes

2024-01-03 11:53 UTC, merged