[HOTFIX]Export fields of NotificationStatusReport
kyma-incubator/compass pull request #3466
Opened 2023-11-14 07:56 UTC by StanislavStefanov

**Description**

Changes proposed in this pull request:
- Export fields of NotificationStatusReport
- Add NotificationStatusReport to ConfigMutator and DestinationCreator inputs

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-11-14 08:01 UTC, StanislavStefanov commented
/retest

2023-11-14 12:58 UTC, ivantenevvasilev approved these changes

2023-11-14 13:19 UTC, PetarTodorovv requested changes

2023-11-14 13:19 UTC, PetarTodorovv commented on components/director/pkg/formationconstraint/formation_constraint_input.go
> +	NotificationStatusReportAddress        uintptr                  `json:"notification_status_report_address"`
`NotificationStatusReportMemoryAddress`? to be consistent with other fields
P.S. Valid for the same field in the destination creator input

2023-11-15 14:19 UTC, PetarTodorovv approved these changes

2023-11-15 14:59 UTC, merged