[WIP] Introduce contains scenario group formation constraint operator
kyma-incubator/compass pull request #3471
Opened 2023-11-15 11:35 UTC by ivantenevvasilev

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**
- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2023-11-15 11:49 UTC, ivantenevvasilev commented
/retest

2023-11-15 16:14 UTC, ivantenevvasilev commented
/retest

2023-11-17 07:06 UTC, ivantenevvasilev commented
/retest

2023-11-17 09:16 UTC, StanislavStefanov requested changes

2023-11-17 12:25 UTC, ivantenevvasilev commented
/test pull-tests-build

2023-11-17 12:28 UTC, ivantenevvasilev commented
/retest

2023-11-20 06:35 UTC, StanislavStefanov requested changes

2023-11-20 06:35 UTC, StanislavStefanov commented on tests/director/tests/notifications/contains_scenario_groups_operator_test.go
> +	t.Logf("Assign application application %q with ID %q to formation %s", appName, otherApp.ID, formationName)
Using appName instead of otherAppName, same applies for some of the next logs

2023-11-20 09:37 UTC, StanislavStefanov approved these changes

2023-11-20 11:28 UTC, dzahariev approved these changes

2023-11-20 11:29 UTC, merged