Implement SetTenantLabel mutation
kyma-incubator/compass pull request #3573
Opened 2024-01-08 11:44 UTC by kaloyanspiridonov

**Description**

Changes proposed in this pull request:
- Introduce a new mutation, SetTenantLabel, that allows setting labels on tenants.
- E2E test that validates that the mutation is working as expected

**Related issue(s)**

- ...

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] Mocks are regenerated, using the automated script

2024-01-08 13:20 UTC, kaloyanspiridonov commented
/test pre-main-compass-gke-benchmark

2024-01-08 14:31 UTC, kaloyanspiridonov commented
/test pre-main-compass-gke-benchmark

2024-01-08 22:26 UTC, kaloyanspiridonov commented
/test pre-main-compass-gke-benchmark

2024-01-09 11:54 UTC, kaloyanspiridonov commented
/test pre-main-compass-gke-benchmark

2024-01-10 09:17 UTC, dragobt requested changes

2024-01-10 09:17 UTC, dragobt commented on components/director/pkg/graphql/schema.graphql
update dependencies as there are changes in the pkg folder and bump values versions

2024-01-23 09:21 UTC, dragobt approved these changes

2024-01-23 09:32 UTC, StanislavStefanov approved these changes

2024-01-23 09:33 UTC, merged