Allow assign only for applications that are ready
kyma-incubator/compass pull request #3581
Opened 2024-01-15 16:10 UTC by ivantenevvasilev

**Description**
Currently we allow applications to be assigned even though they are marked as deleted.

Changes proposed in this pull request:
- disallow assign of applications that are not ready or are being deleted

**Pull Request status**

- [x] Implementation
- [x] Unit tests
- [x] [N/A] Integration tests
- [x] `chart/compass/values.yaml` is updated 
- [x] [N/A] Mocks are regenerated, using the automated script

2024-01-16 07:17 UTC, ivantenevvasilev commented
/test pre-main-compass-gke-benchmark

2024-01-16 07:35 UTC, DimitarPetrov commented on components/director/internal/domain/formation/service.go
> +	}
Maybe we can switch the checks and check first for the deleted at and then for the ready as those properties are correlated anyways. The Delete At timestamps gives more information about why the system is not available and if the deletedAt is set the Ready will always be false.

2024-01-16 08:29 UTC, ivantenevvasilev commented
/test pre-main-compass-gke-benchmark

2024-01-16 12:01 UTC, ivantenevvasilev commented
/test pull-director-unit-test

2024-01-16 14:00 UTC, ivantenevvasilev commented
/test pre-main-compass-gke-benchmark

2024-01-17 08:10 UTC, PetarTodorovv requested changes

2024-01-17 08:10 UTC, PetarTodorovv commented on components/director/internal/domain/formation/assign_formation_test.go
> +		{
`error when the application is not in ready state`?

2024-01-17 08:10 UTC, PetarTodorovv commented on components/director/internal/domain/formation/service.go
> +			return errors.Wrapf(err, "while application %q", objectID)
```suggestion
			return errors.Wrapf(err, "while validating application with ID: %q", objectID)
```

2024-01-18 12:05 UTC, PetarTodorovv approved these changes

2024-01-18 12:07 UTC, merged