Fix WriteTenants mutation
kyma-incubator/compass pull request #3652
Opened 2024-02-13 11:15 UTC by kaloyanspiridonov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2024-02-13 13:50 UTC, kaloyanspiridonov commented
/test pre-main-compass-integration-no-dump

2024-02-14 09:57 UTC, kaloyanspiridonov commented
/retest

2024-02-14 11:33 UTC, kaloyanspiridonov commented
/retest

2024-02-20 13:28 UTC, StanislavStefanov commented
/retest

2024-02-20 13:53 UTC, StanislavStefanov commented
/retest

2024-02-21 13:09 UTC, StanislavStefanov commented
/retest

2024-02-22 07:59 UTC, ivantenevvasilev commented on chart/compass/charts/prometheus-postgres-exporter/values.yaml
> +            description: "Number of TRIAL tenants that have at least one non auto-discovered Application (the tenant is owner and its parent is null) or tenants that have at least on system in state
for all three descriptions - `on system in state` -> `one system in state`, `1 formation` -> `one formation`.

2024-02-23 07:30 UTC, kaloyanspiridonov commented
/retest

2024-02-23 07:47 UTC, ivantenevvasilev commented on tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
> +		subscription.ConfigureTenantTypeAndID(t, httpClient, subscriptionToken, conf.SubscriptionConfig.URL, "customer", "2c4f4a25-ba9a-4dbc-be68-e0beb77a7eb0")
Maybe a comment as to where this ID is coming from?
`// Customer is Test_DefaultCustomer`?

2024-02-23 07:47 UTC, ivantenevvasilev commented on tests/pkg/subscription/utils.go
> +func ConfigureCostObjectUsage(t *testing.T, httpClient *http.Client, subscriptionToken, subscriptionUrl, parentType, parentID string) {
Unused and has the exact same body as `ConfigureTenantTypeAndID`

2024-02-23 08:01 UTC, ivantenevvasilev approved these changes

2024-02-23 08:05 UTC, ivantenevvasilev requested changes
seems like a migration has been merged before this one and the timestamp isn't the latest anymore

2024-02-23 08:13 UTC, ivantenevvasilev submitted a review, later dismissed

2024-02-23 11:33 UTC, StanislavStefanov commented
/retest

2024-02-23 11:34 UTC, alextargov approved these changes

2024-02-23 12:07 UTC, ivantenevvasilev commented
/hold

2024-02-26 06:40 UTC, kaloyanspiridonov commented
/retest

2024-02-26 15:25 UTC, ivantenevvasilev approved these changes

2024-02-27 07:32 UTC, alextargov approved these changes

2024-02-27 07:45 UTC, merged