Remove compass-console
kyma-incubator/compass pull request #3817
Opened 2024-04-16 09:50 UTC by kaloyanspiridonov

**Description**

Changes proposed in this pull request:
- ...

**Related issue(s)**

- ...

**Pull Request status**

- [ ] Implementation
- [ ] Unit tests
- [ ] Integration tests
- [ ] `chart/compass/values.yaml` is updated 
- [ ] Mocks are regenerated, using the automated script

2024-04-16 14:17 UTC, ognyvrac requested changes

2024-04-16 14:17 UTC, ognyvrac commented on installation/cmd/run.sh
> -if [[ -z ${OIDC_HOST} || -z ${OIDC_CLIENT_ID} ]]; then
This whole block should not be removed as the JWT flows will never work locally. The overrides found in `$PATH_TO_COMPASS_OIDC_CONFIG_FILE` could be scoped down only to `idpHost` and they should be overwritten to the new location `.global.oathkeeper...`

2024-04-17 07:23 UTC, kaloyanspiridonov commented
/test pre-main-compass-integration-no-dump

2024-04-17 07:50 UTC, ognyvrac approved these changes

2024-04-17 12:01 UTC, alextargov approved these changes

2024-04-17 13:48 UTC, merged